//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAssortmentCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonement()
        {
            this.Buys = new HashSet<Buy>();
            this.Orders = new HashSet<Order>();
        }
        public string GetInfo
        {
            get
            {
                return $"{CategoryTrainer.Trainer.GetFio}, {CategoryTrainer.Category.Name}, {LessonCount} занятий";

            }
        }

        public int Id { get; set; }
        public int CategoryTrainerId { get; set; }
        public double Price { get; set; }
        public int LessonCount { get; set; }
    
        public virtual CategoryTrainer CategoryTrainer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buy> Buys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
