//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAssortmentCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buy()
        {
            this.Visits = new HashSet<Visit>();
        }
        public string GetInfo
        {
            get
            {
                return $"{User.GetFio}({Abonement.CategoryTrainer.Category.Name} {Abonement.CategoryTrainer.Trainer.GetFio})";

            }
        }

        public string GetColorStatus
        {
            get
            {
                if (LessonsLeftCount == 0)
                    return "#bbbbbb";
                else return "#ffffff";
            }
        }

        public int Id { get; set; }
        public int AbonementId { get; set; }
        public System.DateTime DateTime { get; set; }
        public int LessonsLeftCount { get; set; }
        public string UserName { get; set; }
        public int StatusId { get; set; }
    
        public virtual Abonement Abonement { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
