//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAssortmentCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public int AbonementId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Abonement Abonement { get; set; }
        public virtual User User { get; set; }
    }
}
